import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import {AppProvider} from "@/components/AppContext"
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "ST PIZZA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth bg-black ">
      <body className={`${roboto.className} bg-gradient-to-r from-black via-white to-black`}>
        <main className="max-w-4xl mx-auto border-transparent p-4 min-h-screen bg-white rounded-xl">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="border-t  p-8 text-center  text-gray-500 mt-16">
              &copy; 2025 All rights reserved
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
